name: Deploy to Firebase Hosting on Main Push

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/books-scape/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/books-scape/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13'

      - name: Install Dependencies
        run: npm install

      - name: Build Specific Angular App
        run: npx nx build books-scape --prod

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project angular-books-scape
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
